config/routes.rb
Rails.application.routes.draw do

  resources :articles

  root 'pages#home'

  get 'arte' => 'pages#arte'
  get 'cine' => 'pages#cine'
  get 'eventos' => 'pages#eventos'
  get 'danza' => 'pages#danza'
  get 'musica' => 'pages#musica'
  get 'noticias' => 'pages#noticias'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_attached_file :image

	validates_attachment_content_type :image, 
	content_type:  /^image\/(png|gif|jpeg)/,
	message: "Only images allowed"

	validates :image, attachment_presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :category, :current_issue, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @articles = Article.all
  end

  def arte
    @articles = Article.where(category: 'arte')
  end

  def musica
    @articles = Article.where(category: 'musica')
  end

  def danza
    @articles = Article.where(category: 'danza')
  end

  def cine
    @articles = Article.where(category: 'cine')
  end

  def eventos
    @articles = Article.where(category: 'eventos')
  end

  def noticias
    @articles = Article.where(category: 'noticias')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article, html: {class: "form-signin"}) do |f| %>
  <%= f.error_notification %>
 
 
    <%= f.input :title, required: true, label: false, placeholder: "Title", input_html: {class: "form-control"} %>
    <%= f.input :category, required: true, label: false, placeholder: "Category", input_html: {class: "form-control"} %>
    <%= f.input :content, required: true, label: false, placeholder: "Content", input_html: {class: "form-control", rows: 5} %>
    <br>
    
    <%= f.input :image %>
    
    <div class="checkbox text-center">
    <p>Current Issue</p>
    <%= f.input :current_issue, required: false, label: false %>
    </div>
    <%= f.button :submit, class: "btn btn-primary btn-block" %>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Current issue</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td><%= article.current_issue %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<p>
  <strong>Current issue:</strong>
  <%= @article.current_issue %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href='/'></a>
    </div>
 
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=<%= 'active' if current_page?(arte_path) %>><%= link_to 'arte', arte_path, :class => 'headers' %></li>
        <li class=<%= 'active' if current_page?(musica_path) %>><%= link_to 'música', musica_path, :class => 'headers' %></li>
        <li class=<%= 'active' if current_page?(danza_path) %>><%= link_to 'danza', danza_path, :class => 'headers' %></li>
        <li class=<%= 'active' if current_page?(cine_path) %>><%= link_to 'cine', cine_path, :class => 'headers' %></li>
        <li class=<%= 'active' if current_page?(eventos_path) %>><%= link_to 'eventos', eventos_path, :class => 'headers' %></li>
        <li class=<%= 'active' if current_page?(noticias_path) %>><%= link_to 'noticias', noticias_path, :class => 'headers' %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Busca">
        </div>
        <button type="submit" class="btn btn-default">Go!</button>
      </form>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_logo.html.erb
<%= link_to image_tag("live-logo.png", :width => '200'), root_path, :class => 'logo' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LiveCordoba</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- google fonts -->
  <link href='http://fonts.googleapis.com/css?family=Raleway|Merriweather' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/logo" %>
<%= render "layouts/header" %>
<%= yield %>

</body>
</html>

app/views/pages/_masonry_container.html.erb
<% @articles.each do |a| %>
	
	<%= image_tag a.image.url(:original), class: "img-responsive" %>
	<h2><%= a.title %></h2>
	<p><%= a.content %></p>

<% end %>

app/views/pages/arte.html.erb
<%= render 'masonry_container' %>

app/views/pages/cine.html.erb
<%= render 'masonry_container' %>

app/views/pages/danza.html.erb
<%= render 'masonry_container' %>

app/views/pages/eventos.html.erb
<%= render 'masonry_container' %>

app/views/pages/home.html.erb
<%= render 'masonry_container' %>

app/views/pages/musica.html.erb
<%= render 'masonry_container' %>

app/views/pages/noticias.html.erb
<%= render 'masonry_container' %>